### ISSUE TITLE
Add numpy, scipy and pandas to requirements.txt

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/packaging-scientific-python#3]
I think it would be also reasonable to include numpy, scipy and pandas to the requirements.

Also, on Mac when I install matplotlib, it misses PyQT5. That's probably one more package to install by default.

Do we want `requests`?

**Comment by danielballan** [comment]
Not so sure. I think people should add requirements on a case by case basis. In particular scipy and pandas are very heavy dependencies. How about adding them as examples but commenting them out?

**Comment by mrakitin** [comment]
That's a reasonable concern, @danielballan. I thought since we already had the dependencies in the root of the repo for ipython and matplotlib (which are already heavy), that may make sense to add the other few libs. Anyway, it makes sense to add the proposed libs to the examples, as you mentioned.

**Comment by danielballan** [comment]
Ah, you have raised a potential point of confusion. The `requirements.txt` in the top of the repo just affects building the docs _about_ the cookiecutter. It does not affect the cookiecutter itself. When you create a new project using the cookiecutter, none of the content in the top-level repo comes with it.

**Comment by mrakitin** [comment]
Great! That makes sense then to leave it as is and apply the dependencies per project. Closing.
